### ISSUE TITLE
Problem with self-hosting in Windows

### ISSUE THREAD

**Issue by umuterozan** [beucismis/ozgursozluk#5]
The documentation asks us to run the application with `gunicorn`, but the command throws the following error output.
`ModuleNotFoundError: No module named 'fcntl'`

**[The fcntl module is not available on Windows.](https://stackoverflow.com/questions/45228395/error-no-module-named-fcntl)**

**Comment by beucismis** [comment]
Another solution:`flask run --app ozgursozluk --debug`

**Comment by umuterozan** [comment]
Problem solved by changing api url
